/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YodhaPharmacyRouteImport } from './routes/yodhaPharmacy'
import { Route as IndexRouteImport } from './routes/index'

const YodhaPharmacyRoute = YodhaPharmacyRouteImport.update({
  id: '/yodhaPharmacy',
  path: '/yodhaPharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/yodhaPharmacy': typeof YodhaPharmacyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/yodhaPharmacy': typeof YodhaPharmacyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/yodhaPharmacy': typeof YodhaPharmacyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/yodhaPharmacy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/yodhaPharmacy'
  id: '__root__' | '/' | '/yodhaPharmacy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YodhaPharmacyRoute: typeof YodhaPharmacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yodhaPharmacy': {
      id: '/yodhaPharmacy'
      path: '/yodhaPharmacy'
      fullPath: '/yodhaPharmacy'
      preLoaderRoute: typeof YodhaPharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YodhaPharmacyRoute: YodhaPharmacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
